---
title: "Lesson 1"
author: "Gage Rowden"
date: "2026-09-25"
categories: [post]
image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSBO8xSgW-4qkSWkSM8a-HRkxxAxxjdEfl6ESqdocVmKXin5I5Pd-9Wmmy&s=10
---

# Day 1

## Matthew

### 1:1-17
**How does Matthew begin his gospel account? What does this segment cover?**

- It begins with a geneology from Abraham to Jesus. It only mentions the men within the family tree until Mary where she is mentioned as the husband of Joseph. I find it interesting that Joseph is mentioned given that Jesus was a product of immaculate conception. Is Joseph actually the father of Jesus, or is Jesus the son of God?

### 1:18-25
**What is covered in this segment?**

- The birth of Jesus. Joseph discovered that Mary had become pregnant and planned to "dismiss" her (I'm assuming divorce). After receiving a vision of an angel, he decided to the contrary.

## Luke

### 1:1-4
**What do you learn from these verses about this gospel account?**

- This a more casual, first-person writing form. The author is writing to his friend Theophilus.

### 1:5-25
**What do these verses cover?**

- The story of Zechariah and his wife Elizabeth. She was unable to bear children, but an angel appeared to Zechariah explaining that she would give birth, and the child was to be named John, and he would go on to preach and prepare the people for the Lord. Zechariah questioned how he could confirm this to be true, and for his doubt, he was made a mute.
- Elizabeth eventually gave birth and said "This is what the Lord has done for me when he looked favorably on me and took away the disgrace I have endured among my people." The disgrace she suffered was apparently not being able to conceive.

### 1:26-56
**Summarize**

- The angel, Gabriel, appeared to Mary in this account explaining that she would give birth to Jesus. Mary questioned Gabriel, but he didn't punish her like he did Zechariah.
- Mary met with Elizabeth and her child leapt in her womb. Elizabeth could magically tell that Mary was pregnant with the son of God.
- It ends with a poem about How great and merciful God is.

### 1:57-80
**What are the main points in these verse?**

- Elizabeth gave birth.
- The neighbors tried to name him Zechariah at his circumsicion, but Elizabeth said his name is John.
- Zechariah said idgaf. It was the first time he had spoken since Gabriel visited him.
- Zechariah gave a prophecy that John would become a prophet of God

## John

### 1:1-18
**Who are these verses about and how is he described in verses 1-4, 14, 17-18?**

- God
- 1-4: He is both the Word and with the Word.
- 14: The Word has become flesh (Jesus).
- 17-18: I honestly don't know.

### 1:19-34
**Who is the main character in this segment and what do you learn about him?**

- This segment is about John and his encounter with Jesus. He recognized Jesus as the Messiah on sight alone.

### 1:35-51
**Who takes center stage?**

- Jesus becomes the focus.

## Mark

### 1:1-8
**How does Mark start? What's the first thing you learn from verse 1?**

- We learn Jesus is the son of God.
- It starts with John baptizing in the wilderness when he meets Jesus.

**Who is the main character, and what is his message?**

- John; he says that he baptizes with water but that Jesus will baptize with the Holy Spirit.

### 1:9-11
**What do you learn about Jesus?**

- Jesus learns that he is the son of God?